### ISSUE TITLE
fresh install crash on log_level

### ISSUE THREAD

**Issue by astrofage** [LLNL/Surfactant#137]
**Describe the bug**
Sorry if this has been discussed before. I saw this before and could not reproduce it but just saw it again. I do a basic install using pip3 then surfactant does not exist on path, afterwards launching as a module it gives error

**To Reproduce**
  431  sudo apt-get install python3-pip
  432  pip3 install surfactant
  433  surfactant
  434  python3 -m surfactant
  435  python3 -m surfactant --version
Observe error

**Expected behavior**
Expected to see the version of surfactant

**Screenshots**
```
$ surfactant
surfactant: command not found
$ python3 -m surfactant
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sprocket/.local/lib/python3.10/site-packages/surfactant/__main__.py", line 60, in <module>
    main(log_level="INFO")
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/click/core.py", line 909, in make_context
    ctx = self.context_class(
TypeError: Context.__init__() got an unexpected keyword argument 'log_level'
sprocket@sprocket-Precision-7670:~/proj/CYTRICS/HITACHI/sbom/supros$ python3 -m surfactant --version
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sprocket/.local/lib/python3.10/site-packages/surfactant/__main__.py", line 60, in <module>
    main(log_level="INFO")
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/click/core.py", line 909, in make_context
    ctx = self.context_class(
TypeError: Context.__init__() got an unexpected keyword argument 'log_level'
```

**System Information (please complete the following information):**
$ python3 --version
Python 3.10.13
$ cat /etc/issue
Ubuntu 22.04.3 LTS \n \l

**Additional context**

**Comment by astrofage** [comment]
```
python3 -m surfactant --version
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sprocket/.local/lib/python3.10/site-packages/surfactant/__main__.py", line 60, in <module>
    main(log_level="INFO")
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/click/core.py", line 909, in make_context
    ctx = self.context_class(
TypeError: Context.__init__() got an unexpected keyword argument 'log_level'
```

**Comment by astrofage** [comment]
This resolved itself when I created a venv and installed again via pip3. 
```
  475  python3 -m venv cytrics_venv
  476  sudo apt-get install python3.10-venv
  477  python3 -m venv cytrics_venv
  478  source ./cytrics_venv/bin/activate
  479  pip3 install surfactant
  480  surfactant
```

**Comment by nightlark** [comment]
What version of pip gets installed by `sudo apt-get install python3-pip`? I'm thinking either that version of pip has issues with installing console scripts (and upgrading to a newer pip version will fix it), or since it is a copy of pip coming from the Ubuntu package repository, maybe the `bin` directory it adds scripts to isn't part of `PATH` by default.

The error when running `python3 -m surfactant --version` looks like a bug that should be fixed.

**Comment by astrofage** [comment]
Sorry it's 'surfactant version' I was adding --version but it behaves the same way, same crash. 
```
pip3 -V
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

```
