### ISSUE TITLE
id_hex.py should catch UnicodeDecodeError

### ISSUE THREAD

**Issue by mcutshaw** [LLNL/Surfactant#159]
**Describe the bug**
The id_hex.py identifer does not currently catch errors if the opened file cannot be encoded as UTF-8.
    Traceback (most recent call last):
      File "/home/mcutshaw/code/Surfactant/venv/bin/surfactant", line 8, in <module>
        sys.exit(main())
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
        rv = self.invoke(ctx)
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
      File "/home/mcutshaw/code/Surfactant/surfactant/cmd/generate.py", line 352, in sbom
        if ftype := pm.hook.identify_file_type(filepath=filepath):
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
        return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
        return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
        raise exception.with_traceback(exception.__traceback__)
      File "/home/mcutshaw/code/Surfactant/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
        res = hook_impl.function(*args)
      File "/home/mcutshaw/code/Surfactant/surfactant/filetypeid/id_hex.py", line 82, in identify_file_type
        curr = f.readline()
      File "/usr/lib/python3.10/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 35: invalid continuation byte

**To Reproduce**
1. Create a test file in the extracted helics directory: `dd if=/dev/urandom of=test_file.hex count=200`
2. Create the needed config
3. run `surfactant generate`

**Expected behavior**
We catch the error.

**Comment by mcutshaw** [comment]
Also this is apparently a duplicate of #120, so the linked pull request should fix that one as well.
