### ISSUE TITLE
Crash on no StringTable attribute

### ISSUE THREAD

**Issue by douglasdennis** [LLNL/Surfactant#30]
**Describe the bug**
When running Surfactant on a particular binary it crashed due to an object not having a `StringTable` attribute.
The binary was the "uninstall.exe" binary generated by IDA Freeware 8.3.

**To Reproduce**
1. Run Surfactant on IDA Freeware 8.3 directory
2. Surfactant crashes upon attempting to analyze "uninstall.exe"

**Expected behavior**
Surfactant to run without crashing on the specified binary.

**Screenshots**
Stack trace:
```
Traceback (most recent call last):
  File "/home/doug/projects/Surfactant/venv/bin/surfactant", line 8, in <module>
    sys.exit(main())
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/doug/projects/Surfactant/surfactant/cmd/generate.py", line 267, in sbom
    get_software_entry(
  File "/home/doug/projects/Surfactant/surfactant/cmd/generate.py", line 43, in get_software_entry
    extracted_info_results = pluginmanager.hook.extract_file_info(
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/doug/projects/Surfactant/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/doug/projects/Surfactant/surfactant/infoextractors/pe_file.py", line 30, in extract_file_info
    return extract_pe_info(filename)
  File "/home/doug/projects/Surfactant/surfactant/infoextractors/pe_file.py", line 143, in extract_pe_info
    for st in fi_entry.StringTable:
AttributeError: 'Structure' object has no attribute 'StringTable'
```

**System Information (please complete the following information):**
 - OS: Windows 10 / Ubuntu 20.04 using WSL2

**Additional context**
PR to follow.

**Comment by nightlark** [comment]
Thanks for the bug report and fix. It would be useful to get a small exe file with attributes like this missing for the CI tests to catch regressions.
